namespace Ecommerce.Models;
public enum Category{
    Automotive,
    AutomotiveCarCare,
    AutomotiveReplacementParts,
    AutomotiveToolsAndEquipments,
    Beauty,
    BeautyCosemtics,
    BeautySoap,
    Books,
    BooksFiction,
    BooksNonFiction,
    Electronics,
    ElectronicsPhone,
    ElectronicsPc,
    FashionMen,
    FashionWomen,
    FashionBoys,
    FashionGirls,
    FashionShoes,
    FashionBoysShoes,
    FashionGirlsShoes,
    Home,
    HomeCleaning,
    HomeDecor,
    HomeFurniture,
    HomeKitchen,
    HomeToilet,
    HomeWallArt,
    Movies ,
    Other,
    Software,
    SoftwareEducation,
    SoftwareGames,
    SoftwareLifestyle,
    SoftwareOffice,
    SoftwarePhotography,
    SoftwareSecurity,
    SoftwareVideo,
    Toys,

}
