version: "3.4"

volumes:
  datafiles:

services:
  database:
    image: mysql:8.0.22

    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - datafiles:/var/lib/mysql
      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1/sql"
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: Root0++
      MYSQL_USER: newuser
      MYSQL_PASSWORD: p@ssw0rd1234
      MYSQL_DATABASE: EcommerceDb

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "5000:80"
    restart: always
    environment:
      - DBHOST=databse
      - ASPNETCORE_ENVIRONMENT=Development
