@Api_HostAddress = http://localhost:5271/auth

### Controller test 
GET {{Api_HostAddress}}/test   
 
### Register a new user 
POST {{Api_HostAddress}}/register     
Content-Type: application/json

{
  "FirstName": "name",
  "LastName": "last name",
  "Email": "kasey.kunde21@ethereal.email",
  "Password": "randompassword",
  "ConfirmPassword": "randompassword",
  "DefaultShippingAddress": "Garfield's house", 
  "BillingAddress": "Kizaru"
}

### Login 
POST {{Api_HostAddress}}/login HTTP/1.1          
Content-Type: application/json  
 
{
  "Email": "kasey.kunde21@ethereal.email", 
  "Password": "randompassword"
}

### Refresh Token
POST {{Api_HostAddress}}/refresh HTTP/1.1 
Content-Type: application/json

{
  "AccessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjVkMDU0ZS1jMjUxLTQyNjMtOWIxMS01YjZiOTM2M2NhODkiLCJnaXZlbl9uYW1lIjoibmFtZSIsImZhbWlseV9uYW1lIjoibGFzdCBuYW1lIiwiZW1haWwiOiJrYXNleS5rdW5kZTIxQGV0aGVyZWFsLmVtYWlsIiwibmFtZWlkIjoiM2I1ZDA1NGUtYzI1MS00MjYzLTliMTEtNWI2YjkzNjNjYTg5IiwianRpIjoiMzZiM2VjYzctYjQ0Ny00MTFhLTk5ZDAtNzBhNDY5MzcxNDlkIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJleHAiOjE3MTI2NDg1NjIsImlzcyI6IlJFRCIsImF1ZCI6IlJFRCJ9.4a1qbo0MWyzSl63mu8Im8p_oy8ntKEaX2t_ToFAhU7A",
  "RefreshToken": "YmyEBjdeRNKOePYvet3Pdc5vNeRsBznpxRakGSFJ2bQ="
}

### Register a new user  
POST {{Api_HostAddress}}/register    
Content-Type: application/json

{
  "FirstName": "name",
  "LastName": "last name",
  "Email": "kasey.kunde21@ethereal.email",
  "Password": "randompassword",
  "ConfirmPassword": "randompassword",
  "DefaultShippingAddress": "Garfield's house", 
  "BillingAddress": "Kizaru"
}

### confirm email test
POST https://localhost:7195/auth/confirm-email?userId=08dc522b-2ed8-4bdd-82a1-87408bcd415b&token=CfDJ8KMb1toY37NGgC84jHVbu9mnd3n9JM6oDBaVt%2bXJxO%2byRTwhMbtxfn5gKDlvRwe4C1jROzFgWRG8YYygA7i4j2INjOkUAVgpMtPmeC3Mxda5E6zjwqSFu%2b4mIR2y7NTrsP%2b1Ypu%2byQf8q%2b77Nj7gzEtwdCaNvDBYyNUrlwzEKZ0we3%2f3ox2IZvvOTTxrR4%2bmOw20srgpVa1rM%2f13U809k1HqXVZk3ghc9Wkrzh%2fA%2fEbTHkQtpSXM8i1ZW%2bEcHzGXXA%3d%3d

### login and delete account
POST {{Api_HostAddress}}/login-delete HTTP/1.1            
Content-Type: application/json 
 
{
  "Email": "kasey.kunde21@ethereal.email", 
  "Password": "randompassword"
}

