@Api_HostAddress = http://localhost:5271/auth

### Controller test 
GET {{Api_HostAddress}}/test   
 
### Register a new user  
POST {{Api_HostAddress}}/register   
Content-Type: application/json

{
  "FirstName": "name",
  "LastName": "last name",
  "Email": "kasey.kunde21@ethereal.email",
  "Password": "randompassword",
  "ConfirmPassword": "randompassword",
  "DefaultShippingAddress": "Garfield's house", 
  "BillingAddress": "Kizaru"
}

### Login 
POST {{Api_HostAddress}}/login HTTP/1.1         
Content-Type: application/json 
 
{
  "Email": "kasey.kunde21@ethereal.email", 
  "Password": "randompassword"
}

### Refresh Token
POST {{Api_HostAddress}}/refresh HTTP/1.1 
Content-Type: application/json

{
  "AccessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOGRjNGVlNC1mOWQ2LTQxOTEtOGFkNS1iODZjY2Y3NzI1OGMiLCJnaXZlbl9uYW1lIjoibmFtZSIsImZhbWlseV9uYW1lIjoibGFzdCBuYW1lIiwiZW1haWwiOiJlZGE4NUBldGhlcmVhbC5lbWFpbCIsIm5hbWVpZCI6IjA4ZGM0ZWU0LWY5ZDYtNDE5MS04YWQ1LWI4NmNjZjc3MjU4YyIsImp0aSI6IjA0MGY3MjUwLTNlNDItNDU3YS1iNGFjLWI4MDJhNTAxZmI2MyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkN1c3RvbWVyIiwiZXhwIjoxNzExNjk1MzE3LCJpc3MiOiJSRUQiLCJhdWQiOiJSRUQifQ.6HuxSIsGd_a72W1Z7ylaozAtjAb-pSKK_6gk30_8uBw",
  "RefreshToken": "fr9WwFAMS4lXhObKP5VrzpS77lhCoTsJJRUh9XmpodQ="
}

### Register a new user  
POST {{Api_HostAddress}}/register    
Content-Type: application/json

{
  "FirstName": "name",
  "LastName": "last name",
  "Email": "kasey.kunde21@ethereal.email",
  "Password": "randompassword",
  "ConfirmPassword": "randompassword",
  "DefaultShippingAddress": "Garfield's house", 
  "BillingAddress": "Kizaru"
}

### confirm email test
POST https://localhost:7195/auth/confirm-email?userId=08dc522b-2ed8-4bdd-82a1-87408bcd415b&token=CfDJ8KMb1toY37NGgC84jHVbu9mnd3n9JM6oDBaVt%2bXJxO%2byRTwhMbtxfn5gKDlvRwe4C1jROzFgWRG8YYygA7i4j2INjOkUAVgpMtPmeC3Mxda5E6zjwqSFu%2b4mIR2y7NTrsP%2b1Ypu%2byQf8q%2b77Nj7gzEtwdCaNvDBYyNUrlwzEKZ0we3%2f3ox2IZvvOTTxrR4%2bmOw20srgpVa1rM%2f13U809k1HqXVZk3ghc9Wkrzh%2fA%2fEbTHkQtpSXM8i1ZW%2bEcHzGXXA%3d%3d

### login and delete account
POST {{Api_HostAddress}}/login-delete HTTP/1.1         
Content-Type: application/json 
 
{
  "Email": "kasey.kunde21@ethereal.email", 
  "Password": "randompassword"
}

