@Api_HostAddress = http://localhost:5271/auth

### Controller test 
GET {{Api_HostAddress}}/test
 
### Register a new user
POST {{Api_HostAddress}}/register
Content-Type: application/json

{
  "FirstName": "name",
  "LastName": "last name",
  "Email": "aemail@email.com",
  "Password": "randompassword",
  "DefaultShippingAddress": "Garfield's house",
  "BillingAddress": "Kizaru"
}

### Login

POST {{Api_HostAddress}}/login HTTP/1.1      
Content-Type: application/json
 
{
  "Email": "ttime@email.com",
  "Password": "randompassword"
}

