GET https://localhost:7195/test   
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZW1haWxAZW1haWwuY29tIiwiZ2l2ZW5fbmFtZSI6Im5hbWUiLCJmYW1pbHlfbmFtZSI6Imxhc3QgbmFtZSIsImVtYWlsIjoiYWVtYWlsQGVtYWlsLmNvbSIsImp0aSI6IjE1Mjc4MTNlLTNkNGUtNDYzZS04Y2FkLTNiOGI3MjEwNzBjNyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkN1c3RvbWVyIiwiZXhwIjoxNzExMzU1MjU0LCJpc3MiOiJSRUQiLCJhdWQiOiJSRUQifQ.yKJgKG01TaboLJTCJheL5c2EoFrm7bHR9X2pGouEMKw



###
GET https://localhost:7195/test/service_test 
