@Api_HostAddress = http://localhost:5271/user

PATCH  {{Api_HostAddress}}/update HTTP/1.1  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOGRjNGM5Zi00ZmI1LTQ5YTYtODQ5My1lZTZjZjEyMjZlZDMiLCJnaXZlbl9uYW1lIjoibmFtZSIsImZhbWlseV9uYW1lIjoibGFzdCBuYW1lIiwiZW1haWwiOiJ0dGltZUBlbWFpbC5jb20iLCJuYW1laWQiOiIwOGRjNGM5Zi00ZmI1LTQ5YTYtODQ5My1lZTZjZjEyMjZlZDMiLCJqdGkiOiI1ZTdhOWEzMC00NDlmLTQ1N2YtOGZjMi00YWJkN2VmOGM1MDkiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImV4cCI6MTcxMTM3MDgwMywiaXNzIjoiUkVEIiwiYXVkIjoiUkVEIn0.lLFK6fkHrGar0hyEK6yjDoRrWqGuGavhOivlMRa3vDY
Content-Type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "email": "someEmail@email.com",
  "oldPassword": "randompassword",
  "newPassword": "string",
  "defaultShippingAddress": "string",
  "billingAddress": "string"
}
### 
DELETE {{Api_HostAddress}}/delete    
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOGRjNGUxZC0xNDZhLTRiOTItODNmMC0xNjBiNDM0NDYzNWIiLCJnaXZlbl9uYW1lIjoibmFtZSIsImZhbWlseV9uYW1lIjoibGFzdCBuYW1lIiwiZW1haWwiOiJlZGE4NUBldGhlcmVhbC5lbWFpbCIsIm5hbWVpZCI6IjA4ZGM0ZTFkLTE0NmEtNGI5Mi04M2YwLTE2MGI0MzQ0NjM1YiIsImp0aSI6IjgwYjFiZWViLTgzZmUtNDRjZi1hNmQ0LTliZDEyMmMyYTgyZSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkN1c3RvbWVyIiwiZXhwIjoxNzExNTE2NTk4LCJpc3MiOiJSRUQiLCJhdWQiOiJSRUQifQ.UlmZ2W11topKsOWz58m3MsClsBZ_eeoWs7-lVU8cmY8