@Api_HostAddress = http://localhost:5271/user


GET {{Api_HostAddress}}/test     
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTM5Y2FlYi04ODI3LTRmMzYtOTNmZS1mZTdlNTc2YWQ1NmMiLCJnaXZlbl9uYW1lIjoiQ3VzdG9tZXIiLCJmYW1pbHlfbmFtZSI6IlRoZSBDdXN0b21lciIsImVtYWlsIjoiY3VzdG9tZXJAZW1haWwuZW1haWwiLCJuYW1laWQiOiJhZTM5Y2FlYi04ODI3LTRmMzYtOTNmZS1mZTdlNTc2YWQ1NmMiLCJqdGkiOiI2ZmU0ZWViMC01ZDYwLTQ4MDAtYjZjNi0yOGU5ZTUyNjAyOTYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImV4cCI6MTcxMjMwNjQzMywiaXNzIjoiUkVEIiwiYXVkIjoiUkVEIn0.9n3Yw1hUr1wn7-0bw9tBYEuudDeGL0l2p4O9UyMGh7s
###

PATCH  {{Api_HostAddress}}/update HTTP/1.1  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOGRjNGM5Zi00ZmI1LTQ5YTYtODQ5My1lZTZjZjEyMjZlZDMiLCJnaXZlbl9uYW1lIjoibmFtZSIsImZhbWlseV9uYW1lIjoibGFzdCBuYW1lIiwiZW1haWwiOiJ0dGltZUBlbWFpbC5jb20iLCJuYW1laWQiOiIwOGRjNGM5Zi00ZmI1LTQ5YTYtODQ5My1lZTZjZjEyMjZlZDMiLCJqdGkiOiI1ZTdhOWEzMC00NDlmLTQ1N2YtOGZjMi00YWJkN2VmOGM1MDkiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImV4cCI6MTcxMTM3MDgwMywiaXNzIjoiUkVEIiwiYXVkIjoiUkVEIn0.lLFK6fkHrGar0hyEK6yjDoRrWqGuGavhOivlMRa3vDY
Content-Type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "email": "someEmail@email.com",
  "oldPassword": "randompassword",
  "newPassword": "string",
  "defaultShippingAddress": "string",
  "billingAddress": "string"
}
### Delete user
DELETE http://localhost:5271/user/delete    
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOGRjNTIyOC1kNTIyLTQ3NmEtODZjZi1jNTUzMmEwYzUyMGMiLCJnaXZlbl9uYW1lIjoibmFtZSIsImZhbWlseV9uYW1lIjoibGFzdCBuYW1lIiwiZW1haWwiOiJrYXNleS5rdW5kZTIxQGV0aGVyZWFsLmVtYWlsIiwibmFtZWlkIjoiMDhkYzUyMjgtZDUyMi00NzZhLTg2Y2YtYzU1MzJhMGM1MjBjIiwianRpIjoiYTM5YjBlNzUtNzdmMC00MzgwLWEyZTYtNzAzNzQ3MTRlMDM2IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJleHAiOjE3MTE5NjE1MjUsImlzcyI6IlJFRCIsImF1ZCI6IlJFRCJ9.VPR6c_W7gquj1b61pICfIKCTrsiuwSBONmNyO2QBe0g

### Get user
GET {{Api_HostAddress}}   
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOGRjNTIyNi00NDhjLTQ4OWUtODI2ZC03NDVkN2E1YjI3NzgiLCJnaXZlbl9uYW1lIjoibmFtZSIsImZhbWlseV9uYW1lIjoibGFzdCBuYW1lIiwiZW1haWwiOiJrYXNleS5rdW5kZTIxQGV0aGVyZWFsLmVtYWlsIiwibmFtZWlkIjoiMDhkYzUyMjYtNDQ4Yy00ODllLTgyNmQtNzQ1ZDdhNWIyNzc4IiwianRpIjoiMWQ4ZDdkMTUtMzg0Yi00YTY1LWJmZmUtMThmOWVmZDk5N2IwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJleHAiOjE3MTE5NjA1NTksImlzcyI6IlJFRCIsImF1ZCI6IlJFRCJ9.fbLmwciP9QIh7Gjx8txaDXJT_rCv5OTb42F4riXFsrQ